/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyGUI;

/**
 *
 * @author user
 */
public class Loser extends javax.swing.JPanel {

    /**
     * Creates new form Loser
     */
    public Loser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loser_video = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();

        loser_video.setBackground(new java.awt.Color(0, 102, 102));
        loser_video.setPreferredSize(new java.awt.Dimension(762, 496));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel18.setText("HOME");
        jLabel18.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel15.setText("YOU LOST THE GAME");

        jButton19.setBackground(new java.awt.Color(255, 255, 255));
        jButton19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton19.setText("Play again");

        javax.swing.GroupLayout loser_videoLayout = new javax.swing.GroupLayout(loser_video);
        loser_video.setLayout(loser_videoLayout);
        loser_videoLayout.setHorizontalGroup(
            loser_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loser_videoLayout.createSequentialGroup()
                .addGroup(loser_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loser_videoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loser_videoLayout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jButton19))
                    .addGroup(loser_videoLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel15)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        loser_videoLayout.setVerticalGroup(
            loser_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loser_videoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel18)
                .addGap(13, 13, 13)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loser_video, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loser_video, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel loser_video;
    // End of variables declaration//GEN-END:variables
}
